[esp32s2_base]
extends = esp32_common
custom_esp32_kind = esp32s2

board_build.extra_flags = -DARDUINO_LOLIN_S2_MINI -DBOARD_HAS_PSRAM -DARDUINO_USB_CDC_ON_BOOT=0 -DARDUINO_USB_MODE=0

build_src_filter = 
 ${esp32_common.build_src_filter} - <libpax/> -<nimble/> -<mesh/raspihttp>

monitor_speed = 115200

  
build_flags =
  ${esp32_common.build_flags}
  -DHAS_BLUETOOTH=0
  -DMESHTASTIC_EXCLUDE_PAXCOUNTER
  -DMESHTASTIC_EXCLUDE_BLUETOOTH
  -mtext-section-literals
  
  ;-DCONFIG_ADC_CALI_EFUSE_TP_ENABLE=1
  ;-DCONFIG_ADC_CALI_EFUSE_VREF_ENABLE=1
  ;-include variants/esp32s2/E22_S2_OLED_Enc/fix_adc.h

custom_sdkconfig =
  ${esp32_common.custom_sdkconfig}
  ; ESP32-S2 has no USB-Serial-JTAG peripheral
  CONFIG_TINYUSB_ENABLED=y
  CONFIG_TINYUSB_CDC_ENABLED=y
  ; Вмикаємо сумісність з АЦП калібруванням
  ;CONFIG_ADC_CALI_EFUSE_TP_ENABLE=y
  ;CONFIG_ADC_CALI_EFUSE_VREF_ENABLE=y
  ; Вона не має Bluetooth, вимикаємо софтверне співіснування Wi-Fi/BT
  CONFIG_SW_COEXIST_ENABLE=n
  CONFIG_ESP_COEX_SW_COEXIST_ENABLE=n

lib_ignore = 
  ${esp32_common.lib_ignore}
  NimBLE-Arduino
  libpax

lib_deps =
  ${esp32_common.lib_deps}
  # renovate: datasource=git-refs depName=meshtastic-ESP32_Codec2 packageName=https://github.com/meshtastic/ESP32_Codec2 gitBranch=master
  https://github.com/meshtastic/ESP32_Codec2/archive/633326c78ac251c059ab3a8c430fcdf25b41672f.zip
