[env:E22-S2-OLED-Enc]
extends = esp32s2_base
board = lolin_s2_mini
board_level = extra


build_flags =
  ${esp32s2_base.build_flags}
  -D PRIVATE_HW
  -D OLED_UA
  -I variants/esp32s2/E22_S2_OLED_Enc
  
