[env:E22-S2-OLED-Enc]
extends = esp32s2_base
board = lolin_s2_mini
board_level = extra

; Очищаємо вшиті дефолти з lolin_s2_mini.json, щоб вони не дублювалися в GCC
board_build.extra_flags =

build_flags =
  ${esp32s2_base.build_flags}
  -DPRIVATE_HW
  -DOLED_UA
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=0
  -I variants/esp32s2/E22_S2_OLED_Enc
  
